pipeline {
    agent any

    stages {

        stage('Build') {
            steps {
                dir('shopping-app') {
                    sh 'mvn clean package'
                }
            }
        }

    }
}
