pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                dir('shopping-app') {
                    sh 'chmod +x mvnw'
                    sh './mvnw clean package'
                }
            }
        }
    }
}
